exerciseLog/views.py
from flask import Blueprint, render_template, flash
from flask_login import login_required, current_user
from users.form import ExerciseLogForm
from app import db
from models import ExerciseLog

function_blueprint = Blueprint('log', __name__, template_folder='templates')


"""
    This file contains all the routes for the exercise log functionality
"""
@function_blueprint.route("/log")
@login_required
def log_main():
    return render_template("exerciseLog/Log.html", name=current_user.firstname)



@function_blueprint.route("/log/CreateLog", methods=['GET', 'POST'])
@login_required
def create_log():
    """
    Developed by Harsh
        This route is used to create a new exercise log
    """
    form = ExerciseLogForm()

    if form.validate_on_submit():
        # Create a new ExerciseLog object with the submitted data and the current user's entry_num
        new_exercise_log = ExerciseLog(
            entry_num=form.entry_num.data,
            email=current_user.email,
            date=form.exercise_date.data,
            exercise_type=form.exercise_type.data,
            duration=form.duration.data,
            intensity=form.intensity.data,
            comments=form.comments.data
        )

        # Add the new exercise_log to the database
        db.session.add(new_exercise_log)
        db.session.commit()

        flash('Your exercise has been logged!')
        return render_template("exerciseLog/Log.html", name=current_user.firstname)

    return render_template("exerciseLog/CreateLog.html", form=form)


@function_blueprint.route("/log/ViewLog", methods=['GET', 'POST'])
def view_log():
    """
    Developed by Harsh
        This route is used to view all the exercise logs for the current user
    """
    all_logs = ExerciseLog.query.filter_by(email=current_user.email).all()
    if not all_logs:
        flash('There are no logs to view, Please create a log')
        return render_template("exerciseLog/Log.html", name=current_user.firstname)
    else:
        return render_template("exerciseLog/ViewLog.html", name=current_user.firstname, logs=all_logs)



@function_blueprint.route("/log/DeleteLog", methods=['GET', 'POST'])
@login_required
def delete_log():
    """
    Developed by Harsh
        This route is used to Delete exercise
    """
    # Get all the logs for the current user
    logs_to_delete = ExerciseLog.query.filter_by(email=current_user.email).all()

    # Loops through checking which logs have been selected to delete
    for log in logs_to_delete:
        # Delete the log from the database
        db.session.delete(log)
    db.session.commit()
    return render_template("exerciseLog/DeleteLog.html", name=current_user.firstname)

users/views.py
import bcrypt
from app import db
from flask import Blueprint, render_template, flash, redirect, url_for
from users.form import RegisterForm, LoginForm, PasswordResetForm, ContactForm, DeleteAccountForm
from flask_login import login_user, login_required, logout_user, current_user
from models import User, contact_form, Co2Values

# Sets blueprint folder
users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    Developed by Harsh
        This function is used to register a new user
        :return: renders the register page
    """
    # Registration form
    form = RegisterForm()

    # If request method is POST or form is valid
    if form.validate_on_submit():

        # Checks if email already exists in database
        user = User.query.filter_by(email=form.email.data).first()

        # If email exists redirects user to signup page
        if user:
            flash('Email address already exists')
            return render_template('users/Register.html', form=form)

        # Create new user
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        password=form.password.data,
                        role='user')

        # Add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # Create their carbon emissions
        new_calculation = Co2Values(
                id=new_user.id,
                email=new_user.email,
                transportval=0,
                foodval=0,
                electricalval=0,
                finalval=0
            )
        db.session.add(new_calculation)
        db.session.commit()
        # Sends user to login page
        return redirect(url_for('users.login'))

    return render_template('users/Register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Developed by Harsh
        This function is used to login a user
        :return: renders the login page
    """
    # Login form
    form = LoginForm()

    # Checks the login information being submitted
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if not user or not bcrypt.checkpw(form.password.data.encode('utf-8'), user.password):
            flash('Invalid credentials')
            return render_template('users/Login.html', form=form)

        else:
            login_user(user)


            return redirect(url_for('users.account'))

    return render_template('users/Login.html', form=form)



@users_blueprint.route('/passwordreset', methods=['GET', 'POST'])
def password_reset():
    """
        This function is used to reset a users password
        :return: renders the password reset page
    """
    # Password reset form
    form = PasswordResetForm()

    return render_template('users/PasswordResetForm.html', form=form)


@users_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    """
    Developed by Harsh
        This function is used to contact the admin
        :return: renders the contact page
    """

    # displays contact form
    form = ContactForm()
    # Checks if form is submitted
    if form.is_submitted():
        # Creates new submission
        new_submission = contact_form(
            entry_num=form.entry_num.data,
            message=form.message.data)
        # Adds new submission to database
        db.session.add(new_submission)
        # Commits changes to database
        db.session.commit()
        # Redirects user to contact page
        flash('Your message has been submitted!')
        return redirect(url_for('users.contact'))

    return render_template('users/Contact.html', form=form)


"""
    This function is used to view a users account
    :return: renders the account page
"""


@users_blueprint.route('/account')
@login_required
def account():
    """
    Developed by Catherine
        This function is used to edit a users account
        :return: renders the edit account page
    """
    return render_template('users/Account.html',
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           email=current_user.email)





@users_blueprint.route('/deleteaccount', methods=['GET', 'POST'])
@login_required
def delete_account():
    """
    Developed by Catherine
        This function is used to edit a users account
        :return: renders the edit account page
    """
    # Delete account form
    form = DeleteAccountForm()
    # Checks user info so that only the correct user is deleted
    user = User.query.filter_by(email=form.email.data).first()
    # Checks the data being submitted matches the users info
    if form.validate_on_submit():
        if not user or not bcrypt.checkpw(form.password.data.encode('utf-8'), user.password):
            flash('Invalid credentials')
            return render_template('users/DeleteAccount.html', form=form)
        else:
            # Delete & log out the current user
            db.session.delete(current_user)
            logout_user()
            db.session.commit()
            return redirect(url_for('main'))

    return render_template('users/DeleteAccount.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    """
    Developed by Harsh
        This function is used to logout a user
        :return: redirects to the main page
    """
    # Logs out current user
    logout_user()
    return redirect(url_for('main'))



@users_blueprint.route("/ViewMessages", methods=['GET', 'POST'])
def view_messages():
    """
    Developed by Harsh
        This function is used to view messages
        :return: renders the view messages page
    """
    messages = contact_form.query.all()
    if not messages:
        flash('There are no messages to view')
        return render_template("users/Account.html")
    else:
        return render_template("users/ViewMessages.html", name=current_user.firstname, messages=messages)

templates/users/Account.html
{% extends "base.html" %}
{% block content %}
<body>
    <title>WELCOME {{ firstname }} {{ lastname }}</title>
    <div class = "accountHeading">
        <h1> Welcome {{ firstname }} {{ lastname }}</h1>
    </div>

    <img src="/static/ImageFiles/urf.png">

    <div class="AccountTable">
        <form class="table" method="POST" >
            <h1>Account Details</h1>
            <h2>Email</h2>
                {{ email }}
            <h2>Firstname</h2>
                {{ firstname }}
            <h2>Lastname</h2>
                {{ lastname }}
            <h4><a href="{{ url_for('users.delete_account')}}"> Delete Account </a></h4>
            {% if current_user.role == "admin" %}
                <h4><a href="{{ url_for('users.view_messages')}}"> View Messages </a></h4>
            {% endif %}
        </form>
    </div>
</body>
{% endblock %}

templates/users/Contact.html
{% extends "base.html" %}

{% block content %}
    <body>
        <main>
            <section class="ContactTitle"> Contact Us</section>
            <div class="HomepageLink">
                <a href="{{ url_for('main') }}">Go to Homepage</a>
            </div>

            <section class="ContactHero">
            </section>
            <div class="form-container">
                <form class="ContactForm" method="POST">
                    {{ form.message(class="TextArea", placeholder="Enter Message Here") }}
                        {{ form.submit(class="ContactButton") }}

                </form>
            </div>
        </main>
    </body>

    <div class="ContactMessage">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flashes">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    </div>

{% endblock %}

templates/users/DeleteAccount.html
{% extends "base.html" %}
{% block content %}
  <body>
    <form class="DeleteAccountContainer"  method="POST">
      <h1>Delete Account</h1>
        {{ form.csrf_token() }}
        {{ form.email(class="input", placeholder="Email") }}
        {% for error in form.email.errors %}
            {{ error }}
        {% endfor %}
        {{ form.password(class="input", placeholder="Password") }}
        {% for error in form.password.errors %}
            {{ error }}
        {% endfor %}
        {{ form.submit(class="button") }}
    </form>
  </body>
{% endblock %}

templates/users/Login.html
<style>

    body {
        background-image: url("/static/ImageFiles/haze-over-the-ocean.jpg");
    }

</style>

{% extends "base.html" %}

{% block content %}
    <body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}
    <form class="LoginFormContainer" method="POST">
        <h1>LOGIN</h1>
        {{ form.csrf_token() }}
        {{ form.email(class="input", placeholder="Email") }}
        {% for error in form.email.errors %}
            {{ error }}
        {% endfor %}

        {{ form.password(class="input", placeholder="Password") }}
        {% for error in form.password.errors %}
            {{ error }}
        {% endfor %}
        <div class="recaptcha">
            {{ form.recaptcha }}
        </div>


        <p2><a href="{{ url_for('users.password_reset') }}">Forgot Password?</a></p2>
        {{ form.submit(class="button") }}
    </form>
    </body>
{% endblock %}

templates/users/Logout.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

templates/users/PasswordResetForm.html
<style>
      body{
        background-image: url("/static/ImageFiles/Moon2.jpg");
      }
</style>
{% extends "base.html" %}
{% block content %}
  <body>
    <form class="ResetPasswordFormContainer" method="post">
      <h1>Reset password</h1>
      <input type="text" name="email" placeholder="Email" required>

      <button type="submit">Submit</button>
    </form>
  </body>
{% endblock %}

templates/users/Register.html
<style>
    body{
        background-image: url("/static/ImageFiles/MoonHD.jpg");
        background-size: 300px 300px;
        background-repeat: no-repeat;
        background-position-x: 950px;
        background-position-y: 25px;
    }
</style>
{% extends "base.html" %}
{% block content %}
    <body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
            </div>
        {% endif %}
    {% endwith %}
    <form class="RegisterFormContainer"  method="post">
        <h1>REGISTER</h1>
        <div class="input">
            {{form.csrf_token() }}
            {{ form.email(class="input", placeholder="Email") }}
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div>
            {{ form.firstname(class="input", placeholder="Firstname") }}
            {% for error in form.firstname.errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div>
            {{ form.lastname(class="input", placeholder="Surname") }}
            {% for error in form.lastname.errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div>
            {{ form.password(class="input", placeholder="Password") }}
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div>
            {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
        </div>
        <button type="submit">{{ form.submit }}</button>
    </form>
  </body>

{% endblock %}

templates/users/ViewMessages.html
{% extends "base.html" %}

{% block content %}
    {% if current_user.role == "admin" %}
        <div class="logHero">{{ name }}'s Entries</div>
        <div class="ViewMessages">
            <h2 style ="color:white;">View Messages</h2>
            <div class="returnLog">
                <a href="{{ url_for('log.log_main') }}">Go to Exercise Log</a>
            </div>
            {% if messages %}
                <div class="field">
                    <table class="MessageTable">
                        <tr>
                            <th>Entry_num</th>
                            <th>Message</th>
                        </tr>
                        {% for message in messages %}
                            <tr>
                                <td>{{ message.entry_num}}</td>
                                <td>{{ message.message }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
        </div>
    {% else %}
        <p>You must be an admin to view this page.</p>
    {% endif %}
{% endblock %}