exerciseLog/views.py
from flask import Blueprint, render_template, flash
from flask_login import login_required, current_user
from users.form import ExerciseLogForm
from app import db
from models import ExerciseLog

function_blueprint = Blueprint('log', __name__, template_folder='templates')


"""
    This file contains all the routes for the exercise log functionality
"""
@function_blueprint.route("/log")
@login_required
def log_main():
    return render_template("exerciseLog/Log.html", name=current_user.firstname)



@function_blueprint.route("/log/CreateLog", methods=['GET', 'POST'])
@login_required
def create_log():
    """
    Developed by Harsh
        This route is used to create a new exercise log
    """
    form = ExerciseLogForm()

    if form.validate_on_submit():
        # Create a new ExerciseLog object with the submitted data and the current user's entry_num
        new_exercise_log = ExerciseLog(
            entry_num=form.entry_num.data,
            email=current_user.email,
            date=form.exercise_date.data,
            exercise_type=form.exercise_type.data,
            duration=form.duration.data,
            intensity=form.intensity.data,
            comments=form.comments.data
        )

        # Add the new exercise_log to the database
        db.session.add(new_exercise_log)
        db.session.commit()

        flash('Your exercise has been logged!')
        return render_template("exerciseLog/Log.html", name=current_user.firstname)

    return render_template("exerciseLog/CreateLog.html", form=form)


@function_blueprint.route("/log/ViewLog", methods=['GET', 'POST'])
def view_log():
    """
    Developed by Harsh
        This route is used to view all the exercise logs for the current user
    """
    all_logs = ExerciseLog.query.filter_by(email=current_user.email).all()
    if not all_logs:
        flash('There are no logs to view, Please create a log')
        return render_template("exerciseLog/Log.html", name=current_user.firstname)
    else:
        return render_template("exerciseLog/ViewLog.html", name=current_user.firstname, logs=all_logs)



@function_blueprint.route("/log/DeleteLog", methods=['GET', 'POST'])
@login_required
def delete_log():
    """
    Developed by Harsh
        This route is used to Delete exercise
    """
    # Get all the logs for the current user
    logs_to_delete = ExerciseLog.query.filter_by(email=current_user.email).all()

    # Loops through checking which logs have been selected to delete
    for log in logs_to_delete:
        # Delete the log from the database
        db.session.delete(log)
    db.session.commit()
    return render_template("exerciseLog/DeleteLog.html", name=current_user.firstname)

templates/exerciseLog/CreateLog.html
{% extends "base.html" %}



{% block content %}
    <body>
    <div class="CreateLogHero"> CREATE LOG</div>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        <form class="CreateLog" method="POST">
            {{ form.csrf_token }}
            <a href="{{ url_for('log.log_main') }}">Back To Exercise Log</a>
            <section class="input">
                {{ form.exercise_type.label }}
                {{ form.exercise_type(class="input", placeholder="Exercise Type:", style="color:black") }}
                {% for error in form.exercise_type.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </section>
            <section class="input">
                {{ form.intensity.label }}
                {{ form.intensity(class="input", placeholder="Intensity:", style="color:black") }}
                {% for error in form.intensity.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </section>

            <section class="input">
                {{ form.duration.label }}
                {{ form.duration(class="input", placeholder="Duration:", style="color:black") }}
                {% for error in form.duration.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </section>

            <section class="input">
                {{ form.exercise_date.label }}
                {{ form.exercise_date(class="input", placeholder="Date:", style="color:black") }}
                {% for error in form.exercise_date.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </section>

            <section class="textarea">
                {{ form.comments.label }}
                {{ form.comments(class="input", placeholder="Comments", style="color:black") }}
                {% for error in form.comments.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </section>
            {{ form.submit(class="button") }}
        </form>
    </body>
{% endblock %}

templates/exerciseLog/DeleteLog.html
{% extends "base.html" %}

{% block content %}
    <body>
    <div class="logHero">{{ name }}'s Entries</div>
    <div class="ViewLogpage">
    <h2 style ="color:white;">Delete Logs</h2>
     <a href="{{ url_for('log.log_main') }}">Back To Exercise Log</a>
    {% if logs %}
        <div class="field">
            <table class="table">
                <tr>
                    <th>Date</th>
                    <th>Exercise</th>
                    <th>Duration (minutes)</th>
                    <th>Intensity</th>
                    <th>Comments</th>

                </tr>
                {% for log in logs %}
                    <tr>
                        <td>{{ log.date }}</td>
                        <td>{{ log.exercise_type }}</td>
                        <td>{{ log.duration }}</td>
                        <td>{{ log.intensity }}</td>
                        <td>{{ log.comments }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
    </div>


{% endblock %}

templates/exerciseLog/Log.html
{% extends "base.html" %}

<style>
    .body{
        background: white;
    }
</style>

{% block content %}

<body>

<div class="logHero">{{ name }}'s Exercise Log</div>
 {% with messages = get_flashed_messages() %}
     {% if messages %}
         <section class="logMessages">
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
         </section>
        {% endif %}
{% endwith %}
<div class="logServices">
    <ul>
        <li>
            <h3><a href="{{ url_for('log.view_log')}}">View Logs</a></h3>
        </li>
        <li>
            <h3><a href="{{ url_for('log.create_log')}}">Create Log</a></h3>
        </li>
        <li>
            <h3><a href="{{ url_for('log.delete_log')}}">Delete All Logs</a></h3>
        </li>
    </ul>
</div>
</body>

{% endblock %}

templates/exerciseLog/ViewLog.html
{% extends "base.html" %}

{% block content %}
    <body>
    <div class="logHero">{{ name }}'s Entries</div>
    <div class="ViewLogpage">
        <h2 style ="color:white;">VIEW LOGS</h2>
    <div class="returnLog">
        <a href="{{ url_for('log.log_main') }}">Go to Exercise Log</a>
    </div>
        {% if logs %}
            <div class="field">
                <table class="table">
                    <tr>
                        <th>Date</th>
                        <th>Exercise</th>
                        <th>Duration (minutes)</th>
                        <th>Intensity</th>
                        <th>Comments</th>
                    </tr>
                    {% for log in logs %}
                        <tr>
                            <td>{{ log.date }}</td>
                            <td>{{ log.exercise_type }}</td>
                            <td>{{ log.duration }}</td>
                            <td>{{ log.intensity }}</td>
                            <td>{{ log.comments }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>


{% endblock %}